[package]
name = "raytrace"
version = "0.1.0"
authors = ["pluto"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.22.0-alpha1"
gl = "0.12.0"
rand = "0.6.5"
rayon = "1.1.0"

[dependencies.cgmath]
version = "0.17.0"